server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Cache estático
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|mp3|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # PWA manifest e service worker
    location /manifest.json {
        add_header Cache-Control "no-cache";
    }
    location /service-worker.js {
        add_header Cache-Control "no-cache";
    }
}
